### ISSUE TITLE
Some channels Manifest Error 

### ISSUE THREAD

**Issue by pgebbon** [pgebbon/pgebbon.github.io#4]
With playerjs some live stream have manifest error  on android devices. iOS all works well.

To try test.html with videojs player

**Comment by AllwinFranklin** [comment]
Are you sure, is every channel working fine on IOS devices?

- I tried the link of [**_salvation tv_**](https://www.hlsplayer.net/#type=m3u8&src=https%3A%2F%2Fd39bpvuye592vg.cloudfront.net%2Flive.m3u8) (1st channel) on www.hlsplayer.net/ and it's not working.


Kindly check the [**_CORS error_**](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) at the bottom of the Image

![image](https://user-images.githubusercontent.com/50925874/149612898-4cfc1c8f-7356-4411-810a-5b28a48cb610.png)

We don't have permission to access their content.


Please attach the screen of salvation tv in working state in IOS stage.

**Comment by AllwinFranklin** [comment]
I tried integrating VideoJs into the site. Now new issues raising, 
- Video player goes to fun screen, but video is still in small size.
![image](https://user-images.githubusercontent.com/50925874/149615082-7a735345-f774-4122-b99b-9698d19bad81.png)

- increase in page load time

- Getting unnecessary Controls
![image](https://user-images.githubusercontent.com/50925874/149615107-1672e50a-3e37-407c-aac9-511a4762e4a9.png)


and it seems like there's no benefit in changing from Player.Js to Video.Js

Do you find any benefits, please let me know, we will work further.

**Comment by pgebbon** [comment]
Hi Allwin 
Salvation TV works on IOS 
![4D60367A-E186-40C7-8248-841382C8F937](https://user-images.githubusercontent.com/31389206/149621471-373d4f11-1753-4985-a063-67887de2f532.jpeg)

The videojs is not much of a benefit for now what we have here is good with playerjs
