### ISSUE TITLE
Collapsible Channels Category 

### ISSUE THREAD

**Issue by pgebbon** [pgebbon/pgebbon.github.io#6]
Looking to make the channels category collapsible for quick navigation to pick a channel

**Comment by AllwinFranklin** [comment]
Noted.

**Comment by pgebbon** [comment]
I used the PlayerJS and made the playlists to move to outer container menu.html 
@AllwinFranklin I tried with the image menu in index.html single channels are displayed. when I try “span” in place of “div” was able to create collapsible content but the images background gets changed so would like you to see how to make it look the same as is with collapsible category

**Comment by AllwinFranklin** [comment]
I checked your site. **https://pgebbon.github.io/menu.html**.

This is to make it clear, 
Do I wanna change this layout 
![image](https://user-images.githubusercontent.com/50925874/151123108-31638a48-410a-4f7c-98a2-5cc328cc7895.png)
to 
![image](https://user-images.githubusercontent.com/50925874/151123182-41008aeb-6051-4b8f-b942-cab51bd068c0.png)

# But those channels should be under your collapsable menu, Am I right?

**Comment by pgebbon** [comment]
Well I would like the index.html / test.html with collapsible menu

menu.html is just for showing the collapsible menu
